### PR TITLE
fix: logger can handle circular objects

### LINKED ISSUE #1010: JSON.stringify fails with circular objects
**Describe the bug**:
The debug log currently throws the following kind of exception:

```
threatdragon-1  | TypeError: Converting circular structure to JSON
threatdragon-1  |     --> starting at object with constructor 'Socket'
threatdragon-1  |     |     property 'parser' -> object with constructor 'HTTPParser'
threatdragon-1  |     --- property 'socket' closes the circle
threatdragon-1  |     at JSON.stringify (<anonymous>)
```

This is a direct result of the changes I commited in [Issue 999](https://github.com/OWASP/threat-dragon/issues/999) and [PR 1000](https://github.com/OWASP/threat-dragon/pull/1000).
I am sorry, I didn't pay propper attention...

**Expected behaviour**:
The log should be able to handle circular objects without throwing exceptions.

**Environment**:

- Version: latest

**To Reproduce**:
Have the debug log enabled and try to open a threat model

### PR DESCRIPTION
**Pull request by ch-lepp**
**Summary**:
This PR attempts to solve issue, and closes #1010  
Objects are being preprocessed before logging, so that circularities can be removed.

**Description for the changelog**:
New method for logger to handle circular objects before logging.

### CODE REVIEW

**Comment by jgadsden** [comment]
thanks @ch-lepp , tell me when you want this reviewed

**Comment by ch-lepp** [comment]
Or maybe now  -  I added a unit test to ensure the new method works as intended

**Comment by ch-lepp** [comment]
@jgadsden please feel free to review

**Review by jgadsden — APPROVED** [review]
thanks for these changes to the logger @ch-lepp , I will go ahead and merge

**Comment by ch-lepp** [comment]
Thx @jgadsden
I just downloaded the new docker image and the logging now works as intended

**Pull request merged**
