### PR TITLE
Support Custom Gitlab Instance

### PR DESCRIPTION
**Pull request by 4xpl0r3r**
**Summary**:
This PR makes the code supporting custom Gitlab instance, merged 3 `GITLAB_ENTERPRISE_*` configs into 1 `GITLAB_HOST`.

**Description for the changelog**:
1. merge 3 `GITLAB_ENTERPRISE_*` configs into 1 `GITLAB_HOST`.
2. add the `host` parameter for Gitlab `clientOptions` to support custom Gitlab instances.

**Other info**:
I have tested the code, it works well with my community edition gitlab instance. It seems like the config names `GITLAB_ENTERPRISE_*`, which are similar to the Github's, are not proper names for Gitlab because there could be both community edition and enterprise edition of custom Gitlab. Therefore, I merged these 3 configs into 1 `GITLAB_HOST`.

Have a nice day.

### CODE REVIEW

**Comment by 4xpl0r3r** [comment]
This is my example of env file
```env
GITLAB_CLIENT_ID=0000000000000000000000000000000
GITLAB_CLIENT_SECRET=gloas-0000000000000000000000000000000
GITLAB_SCOPE=read_user read_repository write_repository profile read_api api
GITLAB_REDIRECT_URI=http://threat-dragon-instance/api/oauth/return
GITLAB_HOST=http://gitlab-instance
```

**Comment by 4xpl0r3r** [comment]
#947 Ref

**Comment by jgadsden** [comment]
apologies for being slow to review this @4xpl0r3r , the pull request is much appreciated and I hope to look at it this weekend

**Comment by 4xpl0r3r** [comment]
> apologies for being slow to review this @4xpl0r3r , the pull request is much appreciated and I hope to look at it this weekend

Don’t mind, no problem.

**Comment by 4xpl0r3r** [comment]
> @4xpl0r3r I thought we needed the env variables 'ENTERPRISE_HOSTNAME', 'ENTERPRISE_PROTOCOL' and 'ENTERPRISE_PORT' for running gitlab enterprise? This is being discussed in #947 if I understand correctly @steve-winter and @fdellwing ?

I believe we should merge `GITLAB_ENTERPRISE_*` into `GITLAB_HOST` because of the following reasons:

1. There could be both community and enterprise edition of self-hosted gitlab instances. `ENTERPRISE` might be misleading.
2. The underlaying `gitbeaker` is using `clientOptions.auth['host']` to indicate the Gitlab instance to connect, pass the direct `host` option could be more clear than 3 options.

Just my personal understanding, it is ok to keep the original names in case there is any concern I missed.

**Comment by fdellwing** [comment]
I totally missed this PR, so sorry for the late response and thanks for the ping.

I tested the PR and it seems to work fine.

I'm in support of merging the 3 keys into `GITLAB_HOST`. There was no need to use 3 keys in the first place, as all they there used for was to construct the host itself.

**Comment by jgadsden** [comment]
OK, thanks @fdellwing and @4xpl0r3r I will go ahead and merge
Could either of you provide a step by step on how to access GitLab? We have an open issue in the dcumentation: [Add step by step for gitlab access #81](https://github.com/OWASP/www-project-threat-dragon/issues/81)

**Comment by 4xpl0r3r** [comment]
> OK, thanks @fdellwing and @4xpl0r3r I will go ahead and merge Could either of you provide a step by step on how to access GitLab? We have an open issue in the documentation: [Add step by step for gitlab access #81](https://github.com/OWASP/www-project-threat-dragon/issues/81)

Thanks for the merging, I will try to make a guide.

**Pull request merged**
