### PR TITLE
Bugfix/254 site and desktop tests

### LINKED ISSUE #254: td.site and td.desktop tests disabled
**Describe the bug**
This is not a good thing, but I have had to disable td.site and td.desktop tests

**Expected behaviour**
`npm run test:site` and `npm run test:desktop` should start the karma test runner, but instead they just run the pretests
`npm run test:server` still works as epected

**Environment**
 - Version: 1.5.0
 - Platform: both Web App and Desktop App
 - OS: all of MacOS / Windows / Linux
 - Browser: all

**To Reproduce**
`npm run test:site` and `npm run test:desktop` should start the karma test runner and coverage is displayed

**Any additional context, screenshots, etc**
I have disabled these tests because they need a lot of work and they were delaying the release of version 1.5.0
I do feel bad though

### PR DESCRIPTION
**Pull request by lreading**
**Summary**
Enables td.desktop and td.site unit tests

**Description for the changelog**
closes #254 

**Other info**
td.site was more of a karma config update, whereas td.desktop gave me a bit of trouble.  The third party json-rules-engine was not playing nicely under test.  Ideally, unit tests will only cover first party code and all dependencies can be mocked/stubbed.  I added sinon and stubbed out the third party dependency, as well as making some karma config updates.  The tests all seem to be working now.

### CODE REVIEW

**Comment by lreading** [comment]
I did disable 2 tests that were still failing as opposed to investigating more.  No excuses, just wanted to get the tests enabled again. :sweat_smile:

**Review by jgadsden — APPROVED** [review]
Superb, another excellent contribution @lreading and great to see the tests working again

**Comment by jgadsden** [comment]
JointJS is probably next  on the list of fix-ups - it should correct a lot of the vulnerable dependencies.

@lreading if we get JointJS in along with github enterprise and the test fixups then this could be enough for a version 1.5.1 ?

**Comment by lreading** [comment]
> JointJS is probably next on the list of fix-ups - it should correct a lot of the vulnerable dependencies.
> 
> @lreading if we get JointJS in along with github enterprise and the test fixups then this could be enough for a version 1.5.1 ?

Sounds great to me, as long as prepping the releases aren't too much work on you.  At some point we should catch up - Are there things we could do via GitHub Actions that would make the release cut process easier?

I think v2 is still a long ways out as I've had less time recently to work on it.  If we can make the release process easier for v1.x, that'd enable us to push things out as soon as they're ready. :)

**Comment by jgadsden** [comment]
Yes, definitely github actions would make life easier ... I guess to start with building the desktop installers on merge would be very useful. Maybe time for me to look at issue #112 again

**Pull request merged**
