### PR TITLE
replace pnpm with npm

### LINKED ISSUE #637: Look into migrating to npm
**Describe what problem your feature request solves**
need to know how easy it is to migrate to npm from pnpm

**Describe the solution you'd like**
create a branch `move-to-npm` which replaces `pnpm` with `pnpm`

**Additional context**

### PR DESCRIPTION
**Pull request by jgadsden**
**Summary**
This replaces `pnpm` with `npm` in the documentation, github workflows, docker file and package scripts

**Description for the changelog**
replace pnpm with npm

**Other info**
closes #637

### CODE REVIEW

**Comment by jgadsden** [comment]
Draft pull request, without merge, depending on the outcome of discussion #636 npm or pnpm?

**Comment by jgadsden** [comment]
probably need to implement a package script based on [cyclonedx-node-npm](https://github.com/CycloneDX/cyclonedx-node-npm)
closing this for now

**Comment by jgadsden** [comment]
@martinmarsicano we may decide to move back to npm rather than using pnpm
if you would like to review and advise if this disturbs any of your work on Vue3/pinia

**Comment by martinmarsicano** [comment]
I'll try this in the coming days, but shouldn't be a problem.

**Comment by martinmarsicano** [comment]
Confirmed, I merge the changes made in this branch to the one i'm working and it's working ok.

**Comment by jgadsden** [comment]
Superb, thanks @martinmarsicano , i will merge it to main
We have just today released patch version 2.0.2 so this is good timing to put npm back in

**Pull request merged**
