### PR TITLE
V2 development

### PR DESCRIPTION
**Pull request by jgadsden**
**Summary**
This merges version 2.0 development branch into main. This is a work in progress, so please do not merge into main until all conflicts have been resolved

**Description for the changelog**
Merge v2-development branch into main

**Other info**
Versions prior to 2.0 have been preserved on legacy-v1.x branch off main prior to this merge

### CODE REVIEW

**Comment by jgadsden** [comment]
Well, the conflict files are not as bad as I expected
Also note that any commits to v2-development before the main merge will get merged in as well, so it is safe to carry on commits to v2-development for another day or so

**Comment by jgadsden** [comment]
A couple of things that I had to do : 
1. skip the electron test, as I did not want to delete the file @ShubhamPalriwala 
2. added rate limiting to the express (back end server) app; the code analysis security checks asked for it

Otherwise it was just the normal conflicts - I have been robust :)

**Comment by ShubhamPalriwala** [comment]
Lets goooooo! v2 it is!!

**Comment by jgadsden** [comment]
So, it looks good so far - I have run all the commands I can think of on this PR:
* pnpm install
* npm run build
* npm test
* npm run dev:server
* npm run dev:vue
* npm run electron:build
* npm run electron:serve
* npm run start:site
* npm run start:server

The code analysis LGTM will take a while beause it has a lot to chew through ...

**Comment by lreading** [comment]
Interesting catch by LGTM on rate-limiting. I'm a fan where we're hosting the demo instance in Heroku, a little added protection is nice!

**Comment by jgadsden** [comment]
OK, all seems to test correctly and passes the checks so we can merge on Wednesday 9th as planned; probably mid-afternoon GMT ?  Say 12:00 East coast USA / 22:30 Bangalore

**Comment by lreading** [comment]
> OK, all seems to test correctly and passes the checks so we can merge on Wednesday 9th as planned; probably mid-afternoon GMT ? Say 12:00 East coast USA / 22:30 Bangalore

I should be free for about an hour around then.  Please ping me on Slack if anything comes up, as I've been known to lose track of time... If anything needs tidying up afterwards, we can address it later.  So excited to see this moving into main!

**Comment by ShubhamPalriwala** [comment]
+1 to @lreading ! Ping up on Slack if you need any help, I'll be glad to help.

12 hours to go 🚀

**Pull request merged**
