### PR TITLE
tmt2td

### PR DESCRIPTION
**Pull request by tmart234**
**Summary**

Issue #205 
**Description for the changelog**

Feature utility script to convert MS TMT XML models to Threat Dragon JSON models
**Other info**

 parse TMT XML into a python dict that can be dumped directly into Threat Dragon's json format. This script could be merged into desktop app to import MS TMT files directly. Just modify script to pass the JSON object instead of saving to file. Then look for .tm7 file extensions in desktop app and run this script on that MS TMT file. :) happy threat modeling!

### CODE REVIEW

**Comment by jgadsden** [comment]
Excellent to see @tmart234 , just testing it with the TMT example threat model 
[Sample_Threat_Model.txt](https://github.com/OWASP/threat-dragon/files/6892448/Sample_Threat_Model.txt)

**Comment by jgadsden** [comment]
Hello @tmart234 

When I ran it on the TMT7 sample model I got an error with threat mitigation handling. It is probably something I am doing wrong. Do you have your sample .tm7 file that I could try?

```
threat-dragon$ python --version
Python 3.9.5
threat-dragon$ python tmt2td.py 
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Traceback (most recent call last):
  File "tmt2td.py", line 453, in <module>
    main()
  File "tmt2td.py", line 442, in main
    line = get_element(lines, z, root, m_guid)
  File "tmt2td.py", line 225, in get_element
    cell = get_threats(_root, cell, _m_guid)
  File "tmt2td.py", line 371, in get_threats
    threat_dict['mitigation'] = threat_mits
UnboundLocalError: local variable 'threat_mits' referenced before assignment
```

**Review by jgadsden — COMMENTED** [review]
Hello @tmart234 

When I ran it on the TMT7 sample model I got an error with threat mitigation handling. It is probably something I am doing wrong. Do you have your sample .tm7 file that I could try?

```
threat-dragon$ python --version
Python 3.9.5
threat-dragon$ python tmt2td.py 
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Traceback (most recent call last):
  File "tmt2td.py", line 453, in <module>
    main()
  File "tmt2td.py", line 442, in main
    line = get_element(lines, z, root, m_guid)
  File "tmt2td.py", line 225, in get_element
    cell = get_threats(_root, cell, _m_guid)
  File "tmt2td.py", line 371, in get_threats
    threat_dict['mitigation'] = threat_mits
UnboundLocalError: local variable 'threat_mits' referenced before assignment
```

**Comment by tmart234** [comment]
Okay I updated finding the threat's mitigations. Try now! Worked for me

**Review by jgadsden — APPROVED** [review]
Stunningly good, many thanks @tmart234 
Worked perfectly on the TMT7 sample threat model
Do you want to go ahead and merge it into main? Or I can do it if you like? We can squash commits if you wish

We could also raise an issue for including this script into the file menu of Threat Dragon desktop - either as an 'Import' menu item or as the translation function when the user opens a .tm7 file. Either is good, I will go with whatever you think best

**Comment by tmart234** [comment]
Go ahead and merge into main and squash. Thanks

**Pull request merged**
