### PR TITLE
Add ZAP - Baseline Scan 

### PR DESCRIPTION
**Pull request by prakhar-ai**
**Summary**

Made the ZAP - Baseline Scan run on pull/push requests through GitHub Actions

**Description for the changelog**

Added the ZAP - Baseline Scan to the project

### CODE REVIEW

**Review by jgadsden — APPROVED** [review]
Good to see this @prakhar-ai . Is it possible to change the target? At  the moment https://threatdragon.org is generated from @mike-goodwin original github repo, once the pull request has been merged

@mike-goodwin and @andk123 : having said that, maybe it is best to raise a new issue along the lines of 'demo website needs to be updated from new OAWSP github repo' and go with @prakhar-ai  changes as they stand?

**Comment by prakhar-ai** [comment]
@jgadsden Sure, I can change the target. Where should I point it to?

**Comment by jgadsden** [comment]
Hello @prakhar-ai 

Sadly I am not sure of where the target should point to. We do not have an equivalent public site like https://threatdragon.org for this repo, and https://threatdragon.org is no longer being updated.

Would it be good to go ahead and merge this PR, and then raise another issue for sorting out the target?

**Comment by prakhar-ai** [comment]
Yes @jgadsden, I think that makes sense. We should raise another issue for sorting out the target.

**Comment by jgadsden** [comment]
Yes, let us go with that and I can merge this PR. There is the github.io site at https://threatdragon.github.io/ that  we may be able to do something with

Thanks again for this @prakhar-ai

**Pull request merged**
