### PR TITLE
navbar height increased by 10

### PR DESCRIPTION
**Pull request by AtmegaBuzz**
**Summary**
navbar height was littlebit small and in tablet view the navbar was breaking.

**Description for the changelog**
increased the height by 10px now it looks neat.

**Other info**
its my first pr in owasp community looking forward to it

### CODE REVIEW

**Comment by AtmegaBuzz** [comment]
on screen width(915px)
before
after

full screen view
brfore2
after2

**Comment by jgadsden** [comment]
Hello @AtmegaBuzz - looks good to me. Can you also apply this to main? branch v2-development is more of a historical branch now

**Comment by AtmegaBuzz** [comment]
@jgadsden changed the base to main

**Review by lreading — APPROVED** [review]

**Comment by jgadsden** [comment]
Hello @AtmegaBuzz , thanks for this, would you like the honour of merging your pull request?

**Comment by AtmegaBuzz** [comment]
@jgadsden I don't know. i don't have option to merge the pr here

**Comment by jgadsden** [comment]
> @jgadsden I don't know. i don't have the option/permission to merge the pr here. it will be great if i have the option

Do you want to accept the github invite to be a collaborator with Threat Dragon repo? You should have permission then

**Comment by AtmegaBuzz** [comment]
@jgadsden ya sure, i also joined threat dragon slack channel.

**Pull request merged**
