### PR TITLE
Update for Demo Model page

### PR DESCRIPTION
**Pull request by itsdheerajdp**
**Summary**:
Current Behavior of the Demo Model Page:

Screenshot 2024-02-15 232934

And I want to propose a change in this page in order to make it's UI Better. After making changes, our Demo Model Page will look like below

[screen-capture.webm](https://github.com/OWASP/threat-dragon/assets/107138786/3f51bdee-f703-4c59-9ea4-81a8d636402a)

**Description for the changelog**:
Update for Demo Model page

**Other info**:
Closes: #880

### CODE REVIEW

**Comment by itsdheerajdp** [comment]
@jgadsden have a look in this

**Review by jgadsden — CHANGES_REQUESTED** [review]
Hello @itsdheerajdp , I am not sure that this is an improvement. The intention is to have a list of examples / templates, rather than a series of boxes with text labels

**Review by jgadsden — CHANGES_REQUESTED** [review]
The discussion in #880 needs to be resolved before this pull request can be considered

**Comment by jgadsden** [comment]
This does not fit in with the rest of Threat Dragon, so marking this as "Won't Do"

**Pull request closed without merging**
