### PR TITLE
Introducing Bahasa Indonesia Localization: Translation of Vue I18n English Language Code

### PR DESCRIPTION
**Pull request by teguh02**
**Summary**: Translated Vue I18n English language code to Bahasa Indonesia.

This pull request encompasses a comprehensive translation effort aimed at providing support for Bahasa Indonesia within the Vue I18n English language codebase. By leveraging the principles of internationalization and localization, the codebase has been extended to cater to Indonesian-speaking users, thereby enhancing the accessibility and usability of the application for a wider audience.

**Description for the changelog**: 
Translated to Bahasa Indonesia

**Other info**:
- The translation process involved meticulous attention to detail to ensure the accuracy and fidelity of the Bahasa Indonesia equivalents to the original English strings. Every effort was made to maintain consistency and coherence throughout the translation process.
- Careful consideration was given to cultural nuances and linguistic conventions specific to Bahasa Indonesia, ensuring that the translated content aligns seamlessly with the language's idiosyncrasies and user expectations.
- This initiative underscores our commitment to inclusivity and user-centric design, as we strive to accommodate diverse linguistic preferences and facilitate a more immersive and personalized user experience.
- Contributors are encouraged to review the changes and provide feedback or suggestions for further refinement, as we continually strive to optimize and enrich the language support within our application.

### CODE REVIEW

**Review by jgadsden — CHANGES_REQUESTED** [review]
Many thanks for doing this @teguh02 
could you also add Bahasa Indonesia Localization to files:

- td.vue/tests/unit/desktop/menu.spec.js
- td.vue/src/desktop/menu.js

**Comment by teguh02** [comment]
Hi @jgadsden 
I was added Bahasa Indonesia localization to your explanation files, i hope you will check later. 
Feel free if you need more code modification from me.

Thanks

**Comment by jgadsden** [comment]
perfect, many thanks @teguh02 , I will go ahead and merge

**Review by jgadsden — APPROVED** [review]
all good, merging

**Pull request merged**
