### PR TITLE
Initial finnish translation.

### PR DESCRIPTION
**Pull request by mikkolehtisalo**
This pull request contains an Initial Finnish language translation for the user interface.  

After translating the strings I checked how they work on the UI, and did some fine tuning. I did not translate STRIDE etc terms, because I don't think they should be translated. Working with them translated would be probably awkward.

### CODE REVIEW

**Review by jgadsden — CHANGES_REQUESTED** [review]
Hello @mikkolehtisalo , very good to see this translation file, thanks.

There are a couple of other files that need changes for the desktop : `td.vue/src/desktop/menu.js` and `td.vue/tests/unit/desktop/menu.spec.js`
are you OK with making these changes?

**Comment by jgadsden** [comment]
Agreed that terms such as STRIDE, LINDDUN, CIA etc are best left untranslated.

Do not worry about the PR pipeline / Build docker image test failure - that is due to permissions not being high enough

**Comment by mikkolehtisalo** [comment]
That should do it?

**Review by jgadsden — APPROVED** [review]
superb @mikkolehtisalo , that is perfect thank you
do you want to go ahead and merge?

**Comment by jgadsden** [comment]
merging this to main, thanks again @mikkolehtisalo

**Pull request merged**
