### PR TITLE
Create separate back-end package.json

### LINKED ISSUE #74: Create independent package.json for back-end
**Describe what problem your feature request solves**
Create a separate package.json for the back-end code

**Describe the solution you'd like**
As discussed in https://github.com/OWASP/threat-dragon/discussions/69#discussioncomment-660564 and https://github.com/OWASP/threat-dragon/issues/70#issuecomment-827029562 we should have separate package.json files for the front-end and back-end as they have different needs.

**Additional context**
After a little initial investigation, this will be a non-trivial amount of work to attack all at once.  This issue is specific to the back-end code.

### PR DESCRIPTION
**Pull request by lreading**
**Summary**
Created a separate package.json for the back-end code. 

**Description for the changelog**
- Changed the file structure of the back-end code to keep config and application code separate
- Added a separate package.json for the back-end
- Removed unneeded packages and scripts from both package.json files
- Moved back-end tests into the td.server directory
- Updated Dockerfile to include both front end and back end now that the structure is different, and there's different dependencies
- Added .dockerignore (as noted in https://github.com/OWASP/threat-dragon/issues/71#issuecomment-827047005)
- Added codeql config to ensure that we are scanning the correct areas
- Updated .travis.yml to test both front-end and back-end code on commits
- Updated README.md to reflect the new file structure
- Fixed relative paths for server code that broke due to new directory structure
- Closes #74 

**Other info**
I did my best to test all of these changes locally, as well as testing codecov, codeql and travis integrations.  As best I can tell, everything is working as expected.  
I would appreciate someone giving this at least a sanity check, as it is a larger change.  This should be the last major restructuring of code that's blocking me from starting the migration to ES6 :tada:

### CODE REVIEW

**Comment by lreading** [comment]
I'm not sure what codecov is trying to tell me... It says the diff is 100%, but it also shows that the coverage is exactly the same between master and this branch (which is what I would expect).  Is this working as expected, or did I miss something?

**Comment by lreading** [comment]
CodeQL failed on the minified code again.  That shouldn't be included in the repo, and will be addressed with #75 
I intend to make a separate `dist` directory that will be ignored, then untrack the existing bundled / minified code.

**Comment by jgadsden** [comment]
> I'm not sure what codecov is trying to tell me... It says the diff is 100%, but it also shows that the coverage is exactly the same between master and this branch (which is what I would expect). Is this working as expected, or did I miss something?

Hello @lreading , this is working as expected and codecov seems to be happy. I agree that the two new errors from CodeQL can be ignored for now

**Review by jgadsden — APPROVED** [review]
Really good to see this @lreading . The only comment I have is that my system does not have MS IE, and so I get this error when running `npm run test-local`
```
27 04 2021 21:23:34.396:INFO [launcher]: Launching browsers IE with concurrency unlimited
27 04 2021 21:23:34.401:INFO [launcher]: Starting browser IE
27 04 2021 21:23:34.403:ERROR [launcher]: No binary for IE browser on your platform.
  Please, set "IE_BIN" env variable.
==================== Coverage / Threshold summary 
Statements   : 100% ( 0/0 ) Threshold : 90%
Branches     : 100% ( 0/0 ) Threshold : 90%
Functions    : 100% ( 0/0 ) Threshold : 90%
Lines        : 100% ( 0/0 ) Threshold : 90%
```
Feel free to go ahead and merge

**Comment by lreading** [comment]
The IE tests were there before.  I'm developing on a linux system and currently don't have a *working* windows machine available at the moment.  I'm working on that... :sweat_smile: 

Thanks for taking a look!

**Comment by lreading** [comment]
The zap scan failed when this was merged.  I'm re-running the github action.  I'm not sure why it would fail where it's only checking the docs site, and that's not even hosted in this repo?

**Comment by lreading** [comment]
It failed on rerun: https://github.com/OWASP/threat-dragon/runs/2451945756?check_suite_focus=true

`Error: Resource not accessible by integration`

I'll open a separate issue to resolve this, as it looks like it could be a simple fix.

**Pull request merged**
