### PR TITLE
V2/i18n el

### PR DESCRIPTION
**Pull request by kostasadriano**
**Summary**
Greek translation.

**Description for the changelog**
added file el.js in td.vue/src/i18n
edited file index.js in td.vue/src/i18n

**Other info**

### CODE REVIEW

**Comment by jgadsden** [comment]
Looks great to me @kostasadriano - do you want me to test it on my local V2 Threat Dragon?

**Review by jgadsden — COMMENTED** [review]
Superb! Screen shot of Threat Dragon in Greek attached
el-threat-dragon

**Comment by jgadsden** [comment]
I can merge this in @kostasadriano , unless you would like the honour?

**Comment by kostasadriano** [comment]
> I can merge this in @kostasadriano , unless you would like the honour?

Great! I don't see an option to merge, I guess I don't have the appropriate permissions.

**Comment by jgadsden** [comment]
Ah, not yet ... I have sent an invite as you are now a contributor. If you accept the invite then you should have write access @kostasadriano

**Pull request merged**
