### PR TITLE
Resolves issue #1 - Enables Bitbucket Auth and Repo

### LINKED ISSUE #1: Bitbucket auth
This issue has been migrated from : 
https://github.com/mike-goodwin/owasp-threat-dragon/issues/23
and was opened by @dskrvk:

Bitbucket (which my team happens to use) is a fairly popular alternative to Github. Would be great to have an integration with that as well.

### PR DESCRIPTION
**Pull request by steve-winter**
**Summary**:
Resolves issue #1 to support Bitbucket Auth and Repo

**Description for the changelog**:
New Provider and Repository, with unit tests and general documentation updates.

**Other info**:
Uses https://github.com/MunifTanjim/node-bitbucket as Bitbucket repository interface. Feasible to refactor to use a vanilla HTTP integration if desired.

Closes #1

### CODE REVIEW

**Comment by jgadsden** [comment]
looking excellent @steve-winter , I have reviewed as best as I can; next thing is to merge to main if you would like to go ahead?

**Review by jgadsden — APPROVED** [review]
All looks good, thanks for this @steve-winter

**Comment by steve-winter** [comment]
Merged, thanks.

**Comment by steve-winter** [comment]
@jgadsden  - where does https://www.threatdragon.com/#/ get its environment parameters from?

**Pull request merged**
