### PR TITLE
fix: multi-line description

### LINKED ISSUE #468: multiple-line description support
**Describe the bug**

If we have written a multi-line `High level system description`, it will be rendered on a single line in the model and report screens.

**Expected behaviour**

To be rendered in multiple lines in the above screens

**Environment**
 - Version: 2.0.0 (e.g. 1.3.1)
 - Platform: Web App (Web App / Desktop App)
 - OS: MacOS (MacOS / Windows / Linux)
 - Browser: chrome (e.g. chrome, firefox, safari)

**To Reproduce**

- create new model
- write description
- display dashboard & 

**Any additional context, screenshots, etc**

- submit mutiple-line description
  - image
- rendering single-line
  - image

### PR DESCRIPTION
**Pull request by gassara-kys**
**Summary**

Fixed an issue where the Description item did not support multi-line display.

**Description for the changelog**

multi-line rendering of description. fixes #468 

**Other info**

### CODE REVIEW

**Review by jgadsden — APPROVED** [review]
Many thanks for this fix @gassara-kys 
No problem either way, but did you want to apply 4 spaces indent rather than 2 spaces?

**Comment by jgadsden** [comment]
The docker hub failure is probably an expired 'secrets.DOCKERHUB_TOKEN', will raise an issue and fix this in another PR

**Comment by gassara-kys** [comment]
@jgadsden  Thanks for your review.

> No problem either way, but did you want to apply 4 spaces indent rather than 2 spaces?

I'm sorry I was missing formatting consideration. I fixed it 4 spaces indent.

**Comment by jgadsden** [comment]
The docker build failure is not to do with this PR, so going ahead with merge

**Pull request merged**
