### PR TITLE
Adding support for github enterprise *needs testing*

### PR DESCRIPTION
**Pull request by lreading**
**Summary**
Adding support for Github enterprise.  

**Description for the changelog**
#250 - Adds support for Github enterprise by adding the hostname (optionally port and protocol) to the config

**Other info**
This needs to be tested by someone who has access to a Github enterprise account.  I will review docs and see if any updates need to be made there.

### CODE REVIEW

**Comment by lreading** [comment]
Thanks for taking a look Jon! To be clear, my intention is to leave this PR open until we can have it tested by someone with access to an enterprise account. I'm relatively confident that we're not introducing new bugs or regressions, but I'm not comfortable merging this and claiming we support it without someone testing first. :smile:

**Comment by jgadsden** [comment]
I created a free 16 day github enterprise account. It did not help with testing though - I used the cloud hosted offering and this results in a github.com host URL ... so no benefit to us as this is the same as the free account.

We would need a github enterprise account for our own servers to test this. I checked with the ForgeRock enterprise account and we also use the cloud hosted version - so again it has a github.com host

**Comment by lreading** [comment]
Funny, I was looking at the cloud enterprise trial earlier.  That's unfortunate.  I'll shoot a message out in the slack channel tomorrow to see if we have any enterprise users in there that would be willing to lend a hand in testing. :)

**Review by jgadsden — APPROVED** [review]
@danielpops and @lreading , should we now retire this PR? We can then start afresh on  the v2-development branch

**Comment by lreading** [comment]
Closing - Will try again in the v2 codebase (with better logging/output).

**Pull request closed without merging**
