### PR TITLE
Translated in Hindi

### PR DESCRIPTION
**Pull request by professorabhay**

### CODE REVIEW

**Comment by professorabhay** [comment]
Hello @jgadsden, Its Done !!

**Review by jgadsden — APPROVED** [review]
Superb! many thanks @professorabhay , this is a very good thing to have
Please go ahead and merge

**Comment by professorabhay** [comment]
Thanks @jgadsden

**Comment by jgadsden** [comment]
Could you fix the syntax error? line 44 should read:
saveAs: 'मॉडल को इस रूप में सहेजें'
(there is an extra ' at the end of the line)

**Comment by professorabhay** [comment]
Ohh !! 
You did it ??
@jgadsden

**Pull request merged**
