### PR TITLE
Adding EOL notice for v1 in README

### PR DESCRIPTION
**Pull request by lreading**
**Summary**
Adds a notice about v1 EOL and where to find more information on running v1.x

Don't be afraid of providing feedback on this one! I just wanted to get the discussion/idea started, if there's a better way I am 100% behind it!

### CODE REVIEW

**Comment by ShubhamPalriwala** [comment]
I like the idea! Can we also define the tab spaces and basic formatting rules so that we do not have to face any formatting problems!

**Review by jgadsden — APPROVED** [review]
Nicely put, gets my  approval

**Comment by jgadsden** [comment]
I agree @ShubhamPalriwala that it would be good to have some guidelines for the coding style, at the moment we tend to follow the style of the file that we are changing. Did you want to raise an issue for this?

**Comment by lreading** [comment]
I think a separate issue would be great.  We can also tailor the eslint rules and .gitconfig for line endings, indentation, code style, etc. :)

**Review by ShubhamPalriwala — APPROVED** [review]
Lgtm! All hail v1

**Pull request merged**
