### PR TITLE
feat: make github scope configurable

### LINKED ISSUE #8: Private github repositories are not listed in Github repo selection step
This issue has been migrated from : 
https://github.com/mike-goodwin/owasp-threat-dragon/issues/119
and was opened by @rav94 : 

The repository was listed only after I changed the repository permissions to the public mode. Think this would be an important option to have because you are providing the Github credentials expecting to view your private repos as well. Plus people would be reluctant to put their threat model diagrams in public.

### PR DESCRIPTION
**Pull request by omerlh**
**Summary**

Allow to configure github scope by setting `GITHUB_SCOPE` env var - to support private repos, not only public ones.

**Description for the changelog**

fix #8 - allow to configure GITHUB token scope

**Other info**

### CODE REVIEW

**Review by jgadsden — COMMENTED** [review]
This is a really elegant solution @omerlh , many thanks for this.
We will need to document this env var, so I will add some wording before we merge this pull request, unless you have some description already?

**Comment by omerlh** [comment]
Sure, I can also add that -  where should I document it? README.md?

**Comment by jgadsden** [comment]
Could you document it in the environment vars instructions at: setup-env.md ?  That would be great, thanks

**Comment by omerlh** [comment]
Sure, added

**Review by jgadsden — APPROVED** [review]
Looks good, an elegant solution

**Pull request merged**
