### PR TITLE
Providing translation from English to French

### PR DESCRIPTION
**Pull request by andk123**
**Summary**
Provides translation from English to French.

**Description for the changelog**
#297 - Adding EN to FR translation

**Other info**
PR inspired from #315 🙂

### CODE REVIEW

**Comment by andk123** [comment]
@lreading I inspired myself from your previous PR. Let me know if I'm missing anything!

**Comment by jgadsden** [comment]
Good to see @andk123 

We have more text in the proposed threat engine, but we need to discuss what can be done about that . Did you want ot have a look at the threat engine PR and see how feasible a translation would be for `threatengine.js` ?

**Review by lreading — APPROVED** [review]
Looks great.  Thank you again for taking the time to do this!!!!  Would you like the honor of clicking the merge button? :)

**Comment by andk123** [comment]
No problem at all! 👍  @lreading 

& @jgadsden I just had a look, the translation for threatengine.js would be just fine however, I might need some help with the structure of the fr.js for the threat engine. It was handled here using Vue.js, but I'm not sure what would be the best way to handle it in a vanilla js file

**Comment by jgadsden** [comment]
> I just had a look, the translation for threatengine.js would be just fine however, I might need some help with the structure of the fr.js for the threat engine. It was handled here using Vue.js, but I'm not sure what would be the best way to handle it in a vanilla js file

Hello @andk123 - yes, totally agree, I meant to say that we need to look at the threat engine tranlsation at some point, but not for this particular PR

**Pull request merged**
