### PR TITLE
Feature/84 es6 server

### LINKED ISSUE #84: Allow for ES6 development against td.server
**Describe what problem your feature request solves**
`td.server` should allow for ES6 development

**Describe the solution you'd like**
Using babel or a similar technology, the back-end code should be able to handle es6 syntax, such as `import './foobar.js'`

**Additional context**
Rather than doing a large refactor all at once, I think it would make sense to create the infrastructure to support ES6 development first, and then chip away at refactoring existing code.

### PR DESCRIPTION
**Pull request by lreading**
**Summary**
Allow for ES6 development on back-end

**Description for the changelog**
Adding babel to td.server to allow for es6 development

**Other info**
This adds babel and a build process for td.server that allows developers to write back-end code using ES6.
I refactored a single file as an example.

My only concern with this is that whenever you refactor a file, anything that calls it will need to be updated to call the default property or function.  I'm not sure if this makes the code better or worse.... In the long-term, it will likely be better, but makes me want to refactor the whole thing to es6 all at once as opposed to doing it piece by piece.

Closes #84

### CODE REVIEW

**Comment by lreading** [comment]
Need to fix jshint failure

**Comment by lreading** [comment]
Converted to draft for now until I sort out the tests. Moving to mocha for a testing framework is on the roadmap, this may be the time/place to do it.  Jasmine does not play nicely with ES6 modules

**Comment by jgadsden** [comment]
> Converted to draft for now until I sort out the tests. Moving to mocha for a testing framework is on the roadmap, this may be the time/place to do it. Jasmine does not play nicely with ES6 modules

Hello @lreading - it seems that Travis can not find jshint from  https://travis-ci.org/github/OWASP/threat-dragon/builds/768820949 : 

```
npm ERR! code ELIFECYCLE
507npm ERR! errno 2
508npm ERR! owasp-threat-dragon-server@1.3.1 pretest: `jshint --verbose --show-non-errors src`
509npm ERR! Exit status 2
```

**Comment by lreading** [comment]
@jgadsden - There's a few errors in here.  I'm currently refactoring all of the tests and will need to make some other updates to make this work.  I probably shouldn't haven opened this PR yet.  I'll close it for now until it's in a better state.  My apologies!

**Comment by jgadsden** [comment]
Hello @lreading - yes, sorry, my mistake, agreed that the jshint error was because of earlier errors as you said.

**Pull request closed without merging**
