### PR TITLE
Dark Mode implementation

### PR DESCRIPTION
**Pull request by Shubham-Patel07**
**Summary**:
I have tried to implement dark mode with state management

### CODE REVIEW

**Comment by Shubham-Patel07** [comment]
hey i started with dark mode implementation please provide you views, will complete it soon once you confirm and give your feedback

**Review by jgadsden — CHANGES_REQUESTED** [review]
Many thanks @Shubham-Patel07 

when running 'npm test' there seem to be build errors:

```
Building for production...
error  in ./src/store/index.js
Module not found: Error: Can't resolve './modules/theme.js' in '/Users/jon.gadsden/github/pr924/td.vue/src/store'
```
and this is shown in the pipeline tests as well

**Comment by Shubham-Patel07** [comment]
i have reverted the changed but, this pull request has become messy can i just create another pull closing this which includes necessary changes

**Comment by Shubham-Patel07** [comment]
This pull request got messy from my side, so i will create new pull request with new changes , will take care of package.json this time Please consider it.

**Pull request closed without merging**
