### PR TITLE
Enhanced the way threats are portrayed while drawing models

### LINKED ISSUE #889: Threat numbers are dependent on editing unsaved threats.
**Describe the bug**:

threat numbers for next created threats are affected by just clicking unsaved threats. 
**Expected behavior**:

It was expected for the new threats to stick to an incremental sequence when creating them and to be independent on unsaved threats the ones that get applied first get the next available threat number.
**Environment**:

- Version: (2.2.0)
- Platform: (Web App)

**To Reproduce**:

I believe the threat top number should only be affected when saving and creating a new threat. instead of affecting the numbers of new threats irrelevantly which may confuse end users.

**Screenshot for clarification**
image
threat 1 was created then saved then threat 0 was created and not applied then was clicked 3 times then threat 6 (should have been 2) was created and saved

### PR DESCRIPTION
**Pull request by mohamedselbohy**
**Summary**:

threat number generation updated in addition to unsaved threat styling update

**Description for the changelog**:

changed the threat number generation behavior to only update on saving a threat other than each time an unsaved threat is clicked in addition to differentiating unsaved threats with dull grey color to enhance the user readability for threats.

**Other info**:

closes #889

### CODE REVIEW

**Comment by jgadsden** [comment]
Hello @mohamedselbohy 
thanks for the pull request, did you want to have a look at these tests by running `npm test` :
```
tests/unit/components/threatEditDialog.spec.js
components/ThreatEditDialog.vue › updateThreat › updates the data
components/ThreatEditDialog.vue › updateThreat › updates the styles
```

**Comment by mohamedselbohy** [comment]
I fixed the issue, but still I think the test it failed in is incompatible with the way we generate threat number right now; as it expects a threat that is not new and the threat number is zero, and this is no more possible with the new algorithm.

**Comment by mohamedselbohy** [comment]
> @jgadsden  I fixed the issue, but still I think the test it failed in is incompatible with the way we generate threat number right now; as it expects a threat that is not new and the threat number is zero, and this is no more possible with the new algorithm.

**Comment by mohamedselbohy** [comment]
> Hello @mohamedselbohy thanks for the pull request, did you want to have a look at these tests by running `npm test` :
> 
> ```
> tests/unit/components/threatEditDialog.spec.js
> components/ThreatEditDialog.vue › updateThreat › updates the data
> components/ThreatEditDialog.vue › updateThreat › updates the styles
> ```

I fixed the issue, but still I think the test it failed in is incompatible with the way we generate threat number right now; as it expects a threat that is not new and the threat number is zero, and this is no more possible with the new algorithm.

**Comment by jgadsden** [comment]
@mohamedselbohy did you want to revise the tests to fit in with the new way of creating the threats?
these unit tests are there to help us out rather than hold us back, so if you need to delete or change or expand them then please go ahead

**Comment by mohamedselbohy** [comment]
> @mohamedselbohy did you want to revise the tests to fit in with the new way of creating the threats? these unit tests are there to help us out rather than hold us back, so if you need to delete or change or expand them then please go ahead

I apologize, I was unaware that I am allowed to modify the unit test files. However, the test unit is up to date now, and everything is all set.

**Comment by jgadsden** [comment]
@mohamedselbohy  I have created an issue where the actions applied to the threat generation and modification are listed: #899 
we will need to follow that , so am marking this pull request as "Won't Do"

**Review by jgadsden — CHANGES_REQUESTED** [review]
@mohamedselbohy I have created an issue where the actions applied to the threat generation and modification are listed: https://github.com/OWASP/threat-dragon/issues/899
we will need to follow that , so am marking this pull request as "Won't Do"

**Pull request closed without merging**
