### PR TITLE
chore: upgrade SBOM generators

### LINKED ISSUE #963: [CHORE] upgrade SBOM generator
I've seen you are shipping SBOMs with every release :+1: 

I've seen you are using the unmaintained github workflow `CycloneDX/gh-node-module-generatebom` to generate them.
I propose to switch to the maintained [`@cyclonedx/cyclonedx-npm`](https://www.npmjs.com/package/%40cyclonedx/cyclonedx-npm) instead. 
I propose to use [`@cyclonedx/webpack-plugin`](https://www.npmjs.com/package/@cyclonedx/webpack-plugin) for the VueJS frontends

### PR DESCRIPTION
**Pull request by jkowalleck**
**Summary**:

I've seen you are shipping SBOMs with every release :+1: 

I've seen you are using the unmaintained github workflow `CycloneDX/gh-node-module-generatebom` to generate them.
I propose to switch to the maintained [`@cyclonedx/cyclonedx-npm`](https://www.npmjs.com/package/%40cyclonedx/cyclonedx-npm) instead. 
I propose to use [`@cyclonedx/webpack-plugin`](https://www.npmjs.com/package/@cyclonedx/webpack-plugin) for the VueJS frontends

**Description for the changelog**:
chore: upgrade SBOM generators

**Other info**:
fixes #963

### CODE REVIEW

**Review by jgadsden — APPROVED** [review]
good to have this @jkowalleck , and I agree the gh action being used is not the best way to create SBOMs
did you want to fix up this workflow as well?  `.github/workflows/push.yaml`

**Comment by jkowalleck** [comment]
> good to have this @jkowalleck , and I agree the gh action being used is not the best way to create SBOMs did you want to fix up this workflow as well? `.github/workflows/push.yaml`

yep. the idea was to revisit all SBOM generation workflows and upgrade then to a modern maintained system

**Comment by jkowalleck** [comment]
@jgadsden upgrade done. was unable to test successfully, since some unrelated/untouched CI jobs are skipped or dont pass. 

feel free to merge, or pong me in case a rebase is done and changes are required.

**Review by jgadsden — APPROVED** [review]
thanks for applying this to all the SBOM generators @jkowalleck 
going ahead with the merge because the two failing tests are known issues

**Comment by jkowalleck** [comment]
@jgadsden i see something is off in the SBOM process. I will drop a fix soon

**Pull request merged**
