### PR TITLE
document env vars and add dotenv to front end

### LINKED ISSUE #371: v2.x - document environment variables
**Describe what problem your feature request solves**
We have some env vars that are not documented in the read-me files - mostly because they are used for development

**Describe the solution you'd like**
Document the these env vars in the developer notes

**Additional context**
These are not yet documented:
LOG_LEVEL
ENV_FILE
IS_TEST
ELECTRON_NODE_INTEGRATION
WEBPACK_DEV_SERVER_URL

These are already documented in env.md:
GITHUB_CLIENT_ID
GITHUB_CLIENT_SECRET
GITHUB_SCOPE
NODE_ENV
ENCRYPTION_KEYS
ENCRYPTION_JWT_SIGNING_KEY
ENCRYPTION_JWT
PORT
PROTOCOL

### LINKED ISSUE #389: Ensure that PORT environment variable behaves as expected
**Describe what problem your feature request solves**
We have an environment variable PORT that defines the port number that the TD server listens on. If this is changed it is probable that the front end will not be able to access the backend

**Describe the solution you'd like**
Ensure that the PORT environment variable behaves as expected

**Additional context**

### PR DESCRIPTION
**Pull request by jgadsden**
**Summary**
Further documents environment variables. Also td.vue now accesses the dotenv file to use the port and protocol variables

**Description for the changelog**
document env vars and add dotenv to front end

**Other info**

### CODE REVIEW

**Review by lreading — COMMENTED** [review]
Looks great! I'm going to check if we're using that variable in the heroku deployment before we merge this, just in case. :smile:

**Comment by lreading** [comment]
I've updated the Heroku deployment to have the new property name as https.  Could we also update env.md at line 114?

```PROTOCOL_FILE: /run/secrets/protocol```
Should now be:
```SERVER_API_PROTOCOL_FILE: /run/secrets/server_api_protocol```

When checking for file-based env vars (secrets in docker swarm or k8s), it just appends `_FILE` to the property name.  https://github.com/OWASP/threat-dragon/blob/main/td.server/src/env/Env.js#L72

With the new property name, it will need to match.

Great stuff, a lot more clear what it does!

**Comment by jgadsden** [comment]
Thanks @lreading , updated now if that looks all OK to you?

**Comment by lreading** [comment]
No need to apologize for getting stuff done, this is great! Thanks! Looks good to me!

**Pull request merged**
