### PR TITLE
Fixes:Homepage

### PR DESCRIPTION
**Pull request by itsdheerajdp**
**Summary**:
after making changes our Homepage will look like below

Screenshot 2024-02-09 005131

**Description for the changelog**:
maintain the consistency in UI according to dashboard

**Other info**:
Fixes: #866

### CODE REVIEW

**Comment by itsdheerajdp** [comment]
Please check @jgadsden

**Review by jgadsden — APPROVED** [review]
thanks for these changes @itsdheerajdp , certainly improves the look, please go ahead and merge once the unit test is passing

**Review by jgadsden — CHANGES_REQUESTED** [review]
could the unit test be fixed:

```
Summary of all failing tests
FAIL tests/unit/views/homePage.spec.js
HomePage.vue › browser › layout › has a b-container
    expect(received).toBe(expected) // Object.is equality
    Expected: true
    Received: false

      62 |
      63 |             it('has a b-container', () => {
    > 64 |                 expect(wrapper.findComponent(BContainer).exists()).toBe(true);
         |                                                                    ^
      65 |             });
      66 |
      67 |             it('has a jumbotron', () => {

      at Object.<anonymous> (tests/unit/views/homePage.spec.js:64:68)
Test Suites: 1 failed, 95 passed, 96 total
Tests:       1 failed, 22 skipped, 1052 passed, 1075 total
```

**Comment by itsdheerajdp** [comment]
> could the unit test be fixed:
> 
> ```
> Summary of all failing tests
> FAIL tests/unit/views/homePage.spec.js
> HomePage.vue › browser › layout › has a b-container
>     expect(received).toBe(expected) // Object.is equality
>     Expected: true
>     Received: false
> 
>       62 |
>       63 |             it('has a b-container', () => {
>     > 64 |                 expect(wrapper.findComponent(BContainer).exists()).toBe(true);
>          |                                                                    ^
>       65 |             });
>       66 |
>       67 |             it('has a jumbotron', () => {
> 
>       at Object.<anonymous> (tests/unit/views/homePage.spec.js:64:68)
> Test Suites: 1 failed, 95 passed, 96 total
> Tests:       1 failed, 22 skipped, 1052 passed, 1075 total
> ```

@jgadsden  can you please elaborate what exactly changes i need to make

**Comment by jgadsden** [comment]
@itsdheerajdp if you run `npm test` then you will see the test error, which is looking for `b-container` instead of `b-container-fluid`
This patch should fix the test:

```
diff --git a/td.vue/tests/unit/views/homePage.spec.js b/td.vue/tests/unit/views/homePage.spec.js
index 340216ad..c89355fc 100644
--- a/td.vue/tests/unit/views/homePage.spec.js
+++ b/td.vue/tests/unit/views/homePage.spec.js
@@ -60,7 +60,7 @@ describe('HomePage.vue', () => {
                 expect(wrapper.exists()).toBe(true);
             });
 
-            it('has a b-container', () => {
+            it('has a b-container-fluid', () => {
                 expect(wrapper.findComponent(BContainer).exists()).toBe(true);
             });
```

**Comment by itsdheerajdp** [comment]
@jgadsden  i made the requested changes

**Comment by jgadsden** [comment]
hello @itsdheerajdp , the unit tests are still failing, can you consider applying:

```
diff --git a/td.vue/src/views/HomePage.vue b/td.vue/src/views/HomePage.vue
index 92e52b52..9ec85d01 100644
--- a/td.vue/src/views/HomePage.vue
+++ b/td.vue/src/views/HomePage.vue
@@ -1,5 +1,5 @@
 <template>
-    <b-container-fluid>
+    <b-container fluid>
         <b-jumbotron id="welcome-jumbotron">
             <b-row class="text-center mb-2">
                 <b-col md="12">
@@ -32,7 +32,7 @@
                 </b-col>
             </b-row>
         </b-jumbotron>
-    </b-container-fluid>
+    </b-container>
 </template>
```

**Comment by itsdheerajdp** [comment]
@jgadsden  i applied the requested changes but unit tests are still failing

**Review by jgadsden — APPROVED** [review]
all good @itsdheerajdp , if you would like to go ahead and merge the changes
the failing test is because of a lack of permissions when pushing the docker image, I need to sort that out one day

**Pull request merged**
