### PR TITLE
Add DIE Model in addition to existing

### LINKED ISSUE #718: Add DIE security model
**Describe what problem your feature request solves**:
It would be good to have the cloud based infrastructure DIE Model Security added to Threat Dragon:

Distributed: Are systems distributed to allow for scalability while preventing dependence on a single zone?
Immutable: Can the infrastructure be disposed of and replaced in the event of an issue, aka infrastructure as code?
Ephemeral: What’s the period for system reprovisioning, and are assets disposable in the event of a breach?

**Describe the solution you'd like**:
Add DIE alongside CIA, STRIDE, LINDDUN

**Additional context**:
Some [context](https://www.copado.com/devops-hub/blog/making-die-model-security-vs-the-cia-security-triad-complementary-not-competitive)

### PR DESCRIPTION
**Pull request by danield555**
**Summary**:
Integrating DIE allows us to add cloud native security words in out threat modelling session
by using the DIE Model, we get more applicability on the devops team side

**Description for the changelog**:
add new model for DIE Triad

**Other info**:
closes #718

### CODE REVIEW

**Comment by jgadsden** [comment]
Hello @danield555 , did you want to create a [feature request](https://github.com/OWASP/threat-dragon/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.md&title=) for this?

There is a lot more coding needed to get this into the Threat Dragon application, and it may be extending CIA to become DIE+CIA or it may be that DIE is a new category. Interesting blog [here](https://www.copado.com/devops-hub/blog/making-die-model-security-vs-the-cia-security-triad-complementary-not-competitive)

**Review by jgadsden — CHANGES_REQUESTED** [review]
Hello @danield555 
Good to see that DIE is being implemented. There will have to be additions to the i18n files to provide `threats.model.die.distributed`, `threats.model.die.immutable` and `threats.model.die.ephemeral`
this new file has to be included into `td.vue/src/service/threats/models/index.js` and some more fixups eleshwere, are you OK with providing these additions?

**Comment by danield555** [comment]
I will provide the changes within a week, ( possibly under another github identity, if thats ok with you

**Comment by jgadsden** [comment]
OK, thanks @danield555 , in your capable hands

**Comment by jgadsden** [comment]
@danield555 I have added some commits to the PR to fill in the translations and code that is needed to add DIE to the threat selection mechanism
do not worry about the failing test, build of docker image, that is due to permissions

**Review by jgadsden — APPROVED** [review]
This is ready for merge to main branch
run locally and it works, many thanks for this @danield555

**Pull request merged**
