### PR TITLE
Implimentation of Dark mode

### PR DESCRIPTION
**Pull request by Shubham-Patel07**
**Summary**:

This pull request is about the implementation of dark mode using state management.

preview 

*`light mode`*
image

*`dark mode`*
image

I will improve this gradually, please review it and provide your feedback

### CODE REVIEW

**Review by jgadsden — CHANGES_REQUESTED** [review]
could the use of nativeTheme be considered? from this tutorial : https://www.electronjs.org/docs/latest/tutorial/dark-mode

**Comment by Shubham-Patel07** [comment]
Sure, I'll try to look into it and will know more about `nativeTheme`

**Comment by Shubham-Patel07** [comment]
HI @jgadsden,
I've gone through `nativeTheme` and I've got to know that it is specific to electron setup and need to setup electron app on our current configuration.

**Comment by Shubham-Patel07** [comment]
What do you suggest?

**Pull request closed without merging**
